{
  "hash": "ed7ab26e4d964ca245b96937f45e5efd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise on experiments - possible solution\"\nexecute: \n  warning: false\n  message: false\nformat:\n  html\n---\n\n# Libraries and data used\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::i_am(\"content/exercises/experiments/session13-Exercise-Solution.qmd\")\nlibrary(here)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(car)\nlibrary(effectsize)\nlibrary(readr)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreativity_study <- read_csv(here(\"content/exercises/experiments/employee_data.csv\"))\n```\n:::\n\n\n\n# Step 1: Data Exploration\n\n1. Get basic descriptive statistics for the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(creativity_study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  employee_id work_environment creativity_score years_experience department\n        <dbl> <chr>                       <dbl>            <dbl> <chr>     \n1           1 open_office                  65.3               19 HR        \n2           2 open_office                  69.2               15 Marketing \n3           3 open_office                  90.7               17 Finance   \n4           4 open_office                  72.8               11 IT        \n5           5 open_office                  73.6                7 HR        \n6           6 open_office                  92.6               15 Marketing \n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(creativity_study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 75\nColumns: 5\n$ employee_id      <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16…\n$ work_environment <chr> \"open_office\", \"open_office\", \"open_office\", \"open_of…\n$ creativity_score <dbl> 65.27429, 69.23787, 90.70450, 72.84610, 73.55145, 92.…\n$ years_experience <dbl> 19, 15, 17, 11, 7, 15, 6, 14, 7, 10, 5, 6, 16, 11, 4,…\n$ department       <chr> \"HR\", \"Marketing\", \"Finance\", \"IT\", \"HR\", \"Marketing\"…\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(creativity_study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  employee_id   work_environment   creativity_score years_experience\n Min.   : 1.0   Length:75          Min.   : 48.40   Min.   : 1.00   \n 1st Qu.:19.5   Class :character   1st Qu.: 70.22   1st Qu.: 7.00   \n Median :38.0   Mode  :character   Median : 77.53   Median :11.00   \n Mean   :38.0                      Mean   : 78.58   Mean   :10.97   \n 3rd Qu.:56.5                      3rd Qu.: 86.74   3rd Qu.:15.00   \n Max.   :75.0                      Max.   :107.55   Max.   :20.00   \n  department       \n Length:75         \n Class :character  \n Mode  :character  \n                   \n                   \n                   \n```\n\n\n:::\n:::\n\n\n2. Calculate mean and SD of creativity_score by work_environment\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreativity_study %>%\n  group_by(work_environment) %>%\n  summarise(\n    n = n(),\n    mean = round(mean(creativity_score), 2),\n    sd = round(sd(creativity_score), 2),\n    min = min(creativity_score),\n    max = max(creativity_score),\n    .groups = 'drop'\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  work_environment       n  mean    sd   min   max\n  <chr>              <int> <dbl> <dbl> <dbl> <dbl>\n1 flexible_workspace    25  85.1 10.7   59.6 108. \n2 open_office           25  71.6 11.4   48.4  93.4\n3 private_office        25  79.0  9.19  61.1  99.7\n```\n\n\n:::\n:::\n\n\n3. Create a visualization comparing creativity scores across environments\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = creativity_study, \n  mapping = aes(\n    x = work_environment, \n    y = creativity_score, \n    fill = work_environment)\n  ) +\n  geom_boxplot(alpha = 0.7) +\n  geom_jitter(width = 0.2, alpha = 0.5) +\n  stat_summary(fun = mean, geom = \"point\", shape = 23, size = 3, fill = \"white\") +\n  labs(title = \"Creativity Scores by Work Environment\",\n       x = \"Work Environment\",\n       y = \"Creativity Score (0-100)\",\n       subtitle = \"White diamonds show group means\") +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](session13-Exercise-Solution_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n# Step 2: Assumption Checking\n\n1. Check normality of creativity scores within each group\n\nWe can test for normality visually or by using specific tests.\nA common formal test is the Shapiro test, which can be conducted using the \nfunction `shapiro.test()`.\n\nTo conduct the test for each group we can use the function `by()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nby(\n  # The data on which the test will be applied:\n  data = creativity_study$creativity_score, \n  # The groups that should be separated:\n  INDICES = creativity_study$work_environment, \n  # The function to be applied on these subsets:\n  FUN = shapiro.test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncreativity_study$work_environment: flexible_workspace\n\n\tShapiro-Wilk normality test\n\ndata:  dd[x, ]\nW = 0.98913, p-value = 0.9928\n\n------------------------------------------------------------ \ncreativity_study$work_environment: open_office\n\n\tShapiro-Wilk normality test\n\ndata:  dd[x, ]\nW = 0.96745, p-value = 0.5812\n\n------------------------------------------------------------ \ncreativity_study$work_environment: private_office\n\n\tShapiro-Wilk normality test\n\ndata:  dd[x, ]\nW = 0.97686, p-value = 0.8166\n```\n\n\n:::\n:::\n\n\nIf the p-value if this test is larger than our threshold (usually 0.05), we cannot reject the hypothesis that data are normally distributed.\n\n2. Test equality of variances across groups\n\nIf variances differ across groups, we need to use different analysis tools.\nOne common test to check if variances differ is Levene's test, which tests\nthe Null hypothesis of equal variances. We can use the function `leveneTest()`\nfrom the package `car`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(creativity_score ~ work_environment, data = creativity_study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  2  0.3253 0.7234\n      72               \n```\n\n\n:::\n:::\n\n\nWe have specified an 'equation' with our DV on the LHS and the variable defining\nthe groups on the RHS. Since p-values are large, we cannot reject the Null of \nequal variances.\n\n\n3. Create histograms or Q-Q plots to visually inspect assumptions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = creativity_study, mapping = aes(x = creativity_score)) +\n  geom_histogram(bins = 15) +\n  facet_wrap(~work_environment) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](session13-Exercise-Solution_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(creativity_study, aes(sample = creativity_score)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~ work_environment) +\n  labs(title = \"Q-Q Plots by Work Environment\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](session13-Exercise-Solution_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n# Step 3: Statistical Analysis\n\nWe first conduct a ANOVA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_model <- aov(\n  formula = creativity_score ~ work_environment, \n  data = creativity_study)\nsummary(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Df Sum Sq Mean Sq F value   Pr(>F)    \nwork_environment  2   2290  1144.9   10.47 0.000102 ***\nResiduals        72   7870   109.3                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAlternatively, we can use `lm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_model <- lm(creativity_score ~ work_environment, data = creativity_study)\nanova(lm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: creativity_score\n                 Df Sum Sq Mean Sq F value    Pr(>F)    \nwork_environment  2 2289.8 1144.88  10.474 0.0001017 ***\nResiduals        72 7870.0  109.31                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAlternatively, we look at the original regression output, presenting results\nfrom a different perspective:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = creativity_score ~ work_environment, data = creativity_study)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-25.5135  -6.2979  -0.4267   6.3461  22.4383 \n\nCoefficients:\n                               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      85.113      2.091   40.70  < 2e-16 ***\nwork_environmentopen_office     -13.513      2.957   -4.57 1.98e-05 ***\nwork_environmentprivate_office   -6.091      2.957   -2.06    0.043 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.45 on 72 degrees of freedom\nMultiple R-squared:  0.2254,\tAdjusted R-squared:  0.2039 \nF-statistic: 10.47 on 2 and 72 DF,  p-value: 0.0001017\n```\n\n\n:::\n:::\n\n\nFrom the results we can see that there are significant differences across groups.\nBut to know which groups really differ, we need to do a post-hoc comparison:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = creativity_score ~ work_environment, data = creativity_study)\n\n$work_environment\n                                        diff         lwr        upr     p adj\nopen_office-flexible_workspace    -13.512615 -20.5893415 -6.4358885 0.0000583\nprivate_office-flexible_workspace  -6.091277 -13.1680039  0.9854491 0.1055612\nprivate_office-open_office          7.421338   0.3446111 14.4980641 0.0376828\n```\n\n\n:::\n:::\n\n\nFrom the p-values we can see that:\n\n- There is a significant difference between open office and flexible workspace environment, with the latter being more conductive for creativity\n- There is a significant difference between private and open offices, with the latter being more conductive to creativity\n- There is no statistically significant difference between private offices and flexible workspaces, although the latter have a higher creativity score averate\n\nWe can then check the **standardized effect sizes**:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::eta_squared(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nParameter        | Eta2 |       95% CI\n--------------------------------------\nwork_environment | 0.23 | [0.09, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\nThe value for $\\eta^2$ means that the work environment expalains 23% of the variance in the creativity score - a major factor. This interpretation is further supported if we remember Cohen's classification of effect sizes:\n\n- Small effect: $\\eta^2 \\approx 0.01$ \n- Medium effect: $\\eta^2 \\approx 0.06$\n- Large effect: $\\eta^2 \\approx 0.14$\n\nThis suggests that not only is our result statistically significant (as also demonstrated by the results above), but it is also *practically meaningful* as we witness a large effect according to Cohen's classification.\n\nAnd the confidence interval suggests that even in very, very conservative terms\nwe would still witness a medium sized effect!\n\n# Step 4: Interpretation and Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(creativity_study, aes(x = reorder(work_environment, creativity_score), \n                            y = creativity_score, fill = work_environment)) +\n  geom_violin(alpha = 0.6) +\n  geom_boxplot(width = 0.2, alpha = 0.8) +\n  stat_summary(fun = mean, geom = \"point\", size = 3, color = \"white\") +\n  labs(title = \"Employee Creativity by Work Environment\",\n       subtitle = \"Flexible workspaces show highest creativity scores\",\n       x = \"Work Environment\", \n       y = \"Creativity Score (0-100)\",\n       caption = \"White dots show group means; n=25 per group\") +\n  scale_fill_viridis_d(option = \"plasma\") +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        plot.title = element_text(size = 14, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](session13-Exercise-Solution_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nWe obvserve a statistically significant effect of work environment on creativity scores. \nThe post-hoc test has suggested that flexible workspaces produced significantly \nhigher creativity than both open offices and private offices. \n\n# Step 5: Bonus - ANCOVA\n\nWe simply add the variable `years_experience` to the equation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nancova_model <- lm(\n  formula = creativity_score ~ work_environment + years_experience, \n  data = creativity_study)\nsummary(ancova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = creativity_score ~ work_environment + years_experience, \n    data = creativity_study)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-22.8452  -6.6943  -0.8694   7.3467  23.1578 \n\nCoefficients:\n                               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     88.1025     3.1254  28.189  < 2e-16 ***\nwork_environmentopen_office    -13.1553     2.9571  -4.449 3.13e-05 ***\nwork_environmentprivate_office  -5.6148     2.9673  -1.892   0.0625 .  \nyears_experience                -0.2978     0.2322  -1.282   0.2038    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.41 on 71 degrees of freedom\nMultiple R-squared:  0.2429,\tAdjusted R-squared:  0.2109 \nF-statistic: 7.593 on 3 and 71 DF,  p-value: 0.0001787\n```\n\n\n:::\n:::\n\n\nWe can then compare the models like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(lm_model, ancova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: creativity_score ~ work_environment\nModel 2: creativity_score ~ work_environment + years_experience\n  Res.Df    RSS Df Sum of Sq      F Pr(>F)\n1     72 7870.0                           \n2     71 7691.9  1    178.19 1.6448 0.2038\n```\n\n\n:::\n:::\n\n\nThis conducts a so called F-test to answer the following question: \n*\"Does adding years_experience as a covariate significantly improve our ability to predict creativity scores?\"*\n\nHere are the key elements of the comparison:\n\n- Res.Df. changes from 72 to 71 as the extended model estimates one parameter more and the degrees of freedom are therefore reduced by one.\n- RSS is reduced from 7870.0 to 7691.9, meaning that the new model explains more (the unexplained variance gets reduced)\n- The F-test in the last column tests the hypothesis that adding the additional variable does *not* improve our model. Since $p=0.2038$, we cannot reject this hypothesis using conventional levels of statistical significance. \n- Thus, the results from the original model remain valid and it is not necessary to use the more complex model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::Anova(ancova_model, type = \"III\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: creativity_score\n                 Sum Sq Df  F value    Pr(>F)    \n(Intercept)       86084  1 794.6058 < 2.2e-16 ***\nwork_environment   2163  2   9.9811 0.0001514 ***\nyears_experience    178  1   1.6448 0.2038418    \nResiduals          7692 71                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n",
    "supporting": [
      "session13-Exercise-Solution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}