---
title: "Seminar timetable"
date-format: long
date: "2024-02-28"
date-modified: last-modified
execute: 
  freeze: auto
---

# Tentative outline

::: {.callout-important collapse="false"}
## 📢 Important change! (07.06.2024)

-   🗓️Adjusting times after sampling session!
:::

| **\#** | **Date**        | **Day** | **Topic**                                        |
|------------|------------|------------|------------------------------------|
| 1      | 14.03.24        | Thu     | General introduction and installation            |
| 2      | 21.03.24        | Thu     | Introducing the basics of R and R Studio         |
| 3      | 28.03.24        | Thu     | Basic object types in R (learning video)         |
| 4      | 11.04.24        | Thu     | Advanced object types in R (learning video)      |
| 5      | 18.04.24        | Thu     | Recap and practice                               |
| 6      | 19.04.24        | Fri     | Recap and practice                               |
| 7      | 25.04.24        | Thu     | Data visualization                               |
| 8      | 26.04.24        | Fri     | Finish data visualization and Project Management |
| 9      | 02.05.24        | Thu     | Data import (video lecture)                      |
| 10     | 03.05.24        | Fri     | Video lectures on data wrangling.                |
| NN     | 09.05.24        | Thu     | No lecture due to Christi Himmelfahrt            |
| 11     | 10.05.24        | Fri     | Introducing Quarto and R Markdown                |
| 12     | 16.05.24        | Thu     | Recap and practice: Visualization & data preparation    |
| 13     | 30.05.24        | Thu     | Recap and practice: explorative data analysis    |
| NN     | 31.05.24        | Fri     | Cancelled                                        |
| 14     | 06.06.24        | Thu     | Introduction to data analysis                    |
| 15     | 07.06.24        | Fri     | Sampling I                                       |
| 16     | 13.06.24        | Thu     | Sampling II                                      |
| 17     | 14.06.24        | Fri     | Simple linear regression I                       |
| 18     | 20.06.24        | Thu     | Simple linear regression II                      |
| 19     | 21.06.24        | Fri     | Recap and practice                               |
| **NN** | **27.06.24**    | **Mon** | **Final exam; 14:00 – 16:00, HEL 063**           |
| **NN** | **29.08.24**    | **Thu** | **Re-take exam; 14:00 – 16:00, HEL 063**         |

The re-take exam is only for those who have failed the final exam.

<!--

| 20     |         | Fri     | Selected machine learning tools                  |
| 21     |         | Thu     | Open topic                                       |
-->