---
title: Quarto exercises # Also check out line 43
author: Claudius Gräbner-Radkowitsch
date: '2024-05-16'
documentclass: scrartcl
format: 
  html:
    theme: readable
    highlight: tango
    toc: true
    toc_depth: 2
    number_sections: true
  pdf:
    papersize: a4
    toc: true
    toc-depth: 2
    number-sections: true
    include-in-header: 
      text: |
        \usepackage{lmodern} 
        \usepackage{graphicx}
        \usepackage{hyperref}
        \usepackage{url}                
        \usepackage{xcolor}
        \usepackage{booktabs}
        \usepackage{listings}
        \lstloadlanguages{R}
        
        \definecolor{eufblue}{RGB}{0,57,91}
        \definecolor{eufgrey}{RGB}{111,111,111}
        \definecolor{euflightblue}{RGB}{105,170,205}
        
        \hypersetup{
        pdfauthor={Claudius Graebner-Radkowitsch}
        colorlinks=true,
        linkcolor=euflightblue,
        urlcolor=euflightblue
        }
        \usepackage[includehead,includefoot,top=2cm, bottom=1.5cm]{geometry}
        \usepackage[headsepline, footsepline]{scrlayer-scrpage}
        \pagestyle{scrheadings}
        \clearpairofpagestyles
        \ihead{Exercises: Quarto}
        %\chead{Kopfzeile Mitte}
        \ohead{\pagemark} %
        \ifoot{}
        \cfoot{\href{https://euf-datascience-spring24.netlify.app/}{\normalfont\color{eufblue}{Data Science Using R - Spring Semester 2024}}} % Fußzeile Mitte
        \ofoot{} 
        \setkomafont{disposition}{\color{eufblue}\bfseries}
---


Create a new Quarto document where you set the title, date, and the author 
explicitly.
Write a sample text that comprises...

* ...at least one level 1 heading
* ...at least two level 2 headings
* ...a YAML part that specifies that R code remains hidden by default
* ...one R chunk where both the output and the code is printed in the final document
* ...one R chunk that produces a simply ggplot object and where the code producing the plot is hidden

Then do the following:

1. Knit the document to `html` with a floating table of contents and a 
[special theme](https://quarto.org/docs/output-formats/html-themes.html).

2. Make the document available via 
[Netlify Drop](https://app.netlify.com/drop)
and add the possibility to download the underlying Rmd file.
*Note: For Netlify Drop to work, the html file must be called* `index.html`*!*

3. Knit the document to PDF and make sure that it includes a table of contents.

A sample solution for the Rmd file can be found 
[here](https://gist.github.com/graebnerc/f42962b9ecbf9d7a7e6dc5593be691bd) 
(the Netlify version is [here](https://quarto-ex-solution.netlify.app/)).
